### ISSUE TITLE
model/feature urls expired

### ISSUE THREAD

**Issue by anthony123** [alipay/VCSL#2]
hi， when I download model/feat from  vcsl_features_spd_models.txt, I found the file has expired
the errors are as follows:

`<Error>
<Code>AccessDenied</Code>
<Message>Request has expired.</Message>
<RequestId>6242DB5FA4D16F3638A90919</RequestId>
<HostId>bai-copyright.oss-cn-shanghai.aliyuncs.com</HostId>
<Expires>2022-03-19T11:50:27.000Z</Expires>
<ServerTime>2022-03-29T10:11:43.000Z</ServerTime>
</Error>`

**Comment by xcaizewu** [comment]
> hi， when I download model/feat from vcsl_features_spd_models.txt, I found the file has expired the errors are as follows:
> 
> `<Error> <Code>AccessDenied</Code> <Message>Request has expired.</Message> <RequestId>6242DB5FA4D16F3638A90919</RequestId> <HostId>bai-copyright.oss-cn-shanghai.aliyuncs.com</HostId> <Expires>2022-03-19T11:50:27.000Z</Expires> <ServerTime>2022-03-29T10:11:43.000Z</ServerTime> </Error>`

Have you solved the problem？I have the same problem

**Comment by xcaizewu** [comment]
> hi， when I download model/feat from vcsl_features_spd_models.txt, I found the file has expired the errors are as follows:
> 
> `<Error> <Code>AccessDenied</Code> <Message>Request has expired.</Message> <RequestId>6242DB5FA4D16F3638A90919</RequestId> <HostId>bai-copyright.oss-cn-shanghai.aliyuncs.com</HostId> <Expires>2022-03-19T11:50:27.000Z</Expires> <ServerTime>2022-03-29T10:11:43.000Z</ServerTime> </Error>`

Have you solved the problem？I have the same problem 
@anthony123

**Comment by anthony123** [comment]
not yet发自我的手机-------- 原始邮件 --------发件人： xcaizewu ***@***.***>日期： 2022年5月10日周二 12:39收件人： alipay/VCSL ***@***.***>抄送： Warren_liu ***@***.***>, Author ***@***.***>主    题： Re: [alipay/VCSL] model/feature urls expired (Issue #2)



hi， when I download model/feat from vcsl_features_spd_models.txt, I found the file has expired the errors are as follows:

<Error> <Code>AccessDenied</Code> <Message>Request has expired.</Message> <RequestId>6242DB5FA4D16F3638A90919</RequestId> <HostId>bai-copyright.oss-cn-shanghai.aliyuncs.com</HostId> <Expires>2022-03-19T11:50:27.000Z</Expires> <ServerTime>2022-03-29T10:11:43.000Z</ServerTime> </Error>



Have you solved the problem？I have the same problem

**Comment by xcaizewu** [comment]
好的 谢谢 @anthony123

**Comment by geekchen007** [comment]
Have you solved the problem？I have the same problem

**Comment by xcaizewu** [comment]
not yet. I am sending an email to the author @geekchen007

**Comment by xcaizewu** [comment]
Hi, I have a question. How did you extract the features of your video @anthony123 @geekchen007

**Comment by SifengHe** [comment]
Hi everyone! Sorry for late reply. We will provide another stable feature urls (including RMAC, DINO, etc ) before mid-June, and we will also incrementally update the VCSL dataset to make up for some invalid links.

**Comment by lst17640097780** [comment]
Thank you, I'm so glad that you are maintaining this project! @SifengHe

**Comment by Ilikeyou3000** [comment]
插眼

**Comment by mengnan12** [comment]
请问你知道feat from vcsl_features_spd_models.txt这个压缩包的密码吗？

**Comment by Ilikeyou3000** [comment]
4732

**Comment by mengnan12** [comment]
> 

谢谢！

**Comment by vcsl-owner** [comment]
Hi all, we have updated new stable model/feature links.
