### ISSUE TITLE
Some video cannot be downloaded due to copyright limitation.

### ISSUE THREAD

**Issue by KT27-A** [alipay/VCSL#5]
Thanks for your inspiring work. We learned a lot from it. 

When downloading videos, I found that many videos could not be downloaded due to copyright issues. 

May I ask how to download such videos?

**Comment by KT27-A** [comment]
ERROR: [youtube] q7QF3fBwlUc: This video contains content from 上海森宇文化传播有限公司, who has blocked it on copyright grounds

**Comment by xcaizewu** [comment]
can you downloads the pre-model use vcsl_features_spd_models.txt  @Katou2

**Comment by vcsl-owner** [comment]
Hi all, we have updated new stable model/feature links.
