### ISSUE TITLE
please give some details about how to get dino feature.

### ISSUE THREAD

**Issue by wxywb** [alipay/VCSL#9]
thanks for the nice work.
We want to reproduce the feature extraction in this paper. We use [original dino repo](https://github.com/facebookresearch/dino ) to extract and get the embedding dimension size.
- vits16 384
- vits8 384
- vitb16 768
- vitb8 768
- xcit_small_12_p16 384
- xcit_small_12_p8 384
- xcit_medium_24_p16 512
- xcit_medium_24_p8 512
- resnet50 2048

But I found the embedding size in your google drive(17G) is 1536. Could I get the detail how to generate the same embedding as yours?

**Comment by vcsl-owner** [comment]
Our DINO features are generated in the same way as original DINO paper (https://arxiv.org/pdf/2104.14294.pdf) Section 4.2.1. The features are obtained as the concatenation of the output [CLS] token and of the GeM pooled output patch tokens. This results in a 1536d descriptor for ViT-B.

**Comment by wxywb** [comment]
Thanks for your nice reply!
